
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__screenlock_client_glue_h__proxy__H__
#define __sdbuscpp__screenlock_client_glue_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace sgy {
namespace pine {

class screenLock_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "sgy.pine.screenLock";

protected:
    screenLock_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
        proxy_.uponSignal("screenLocked").onInterface(INTERFACE_NAME).call([this](const bool& screenLocked){ this->onScreenLocked(screenLocked); });
    }

    ~screenLock_proxy() = default;

    virtual void onScreenLocked(const bool& screenLocked) = 0;

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
